apiVersion: 1

datasources:
  - name: ClickHouse Analytics
    type: grafana-clickhouse-datasource
    uid: clickhouse-analytics-ds
    orgId: 1
    version: 1
    editable: true
    isDefault: true
    access: proxy
    protocol: native

    jsonData:
        defaultDatabase: events
        host: clickhouse-server
        port: 9000
        username: ${CLICKHOUSE_USER}

    secureJsonData:
        password: ${CLICKHOUSE_PASSWORD}

    readOnly: true